// Code generated by go generate; DO NOT EDIT.
// This file was generated by reset.go

package pkg

func (v *ResetableStruct) Reset() {
	if v == nil {
		return
	}
	v.i = 0
	v.str = ""
	if v.strP != nil {
		*v.strP = ""
	}
	v.s = v.s[:0]
	if v.m != nil {
		clear(v.m)
	}
	if v.child != nil {
		v.child.Reset()
	}
}
