// Code generated by MockGen. DO NOT EDIT.
// Source: go-url-shortener/internal/service/shortifier (interfaces: StringGenerator)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStringGenerator is a mock of StringGenerator interface.
type MockStringGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockStringGeneratorMockRecorder
}

// MockStringGeneratorMockRecorder is the mock recorder for MockStringGenerator.
type MockStringGeneratorMockRecorder struct {
	mock *MockStringGenerator
}

// NewMockStringGenerator creates a new mock instance.
func NewMockStringGenerator(ctrl *gomock.Controller) *MockStringGenerator {
	mock := &MockStringGenerator{ctrl: ctrl}
	mock.recorder = &MockStringGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStringGenerator) EXPECT() *MockStringGeneratorMockRecorder {
	return m.recorder
}

// GetRandomString mocks base method.
func (m *MockStringGenerator) GetRandomString(arg0 int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomString", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRandomString indicates an expected call of GetRandomString.
func (mr *MockStringGeneratorMockRecorder) GetRandomString(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomString", reflect.TypeOf((*MockStringGenerator)(nil).GetRandomString), arg0)
}
