// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: balance_query.sql

package balancerepository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBalance = `-- name: CreateBalance :exec
INSERT INTO public.balance(user_id)
	VALUES ($1)
`

func (q *Queries) CreateBalance(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, createBalance, userID)
	return err
}

const getBalance = `-- name: GetBalance :one
SELECT amount, withdrawn, user_id
	FROM public.balance
	where user_id = $1
`

type GetBalanceRow struct {
	Amount    pgtype.Numeric
	Withdrawn pgtype.Numeric
	UserID    int64
}

func (q *Queries) GetBalance(ctx context.Context, userID int64) (GetBalanceRow, error) {
	row := q.db.QueryRow(ctx, getBalance, userID)
	var i GetBalanceRow
	err := row.Scan(&i.Amount, &i.Withdrawn, &i.UserID)
	return i, err
}

const getWithdrawals = `-- name: GetWithdrawals :many
SELECT order_num, withdraw_amount, user_id, created_at
	FROM public.withdraw_history
	where user_id = $1
`

type GetWithdrawalsRow struct {
	OrderNum       int64
	WithdrawAmount pgtype.Numeric
	UserID         int64
	CreatedAt      pgtype.Timestamp
}

func (q *Queries) GetWithdrawals(ctx context.Context, userID int64) ([]GetWithdrawalsRow, error) {
	rows, err := q.db.Query(ctx, getWithdrawals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWithdrawalsRow
	for rows.Next() {
		var i GetWithdrawalsRow
		if err := rows.Scan(
			&i.OrderNum,
			&i.WithdrawAmount,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertWithdrawal = `-- name: InsertWithdrawal :exec
INSERT INTO public.withdraw_history(order_num, withdraw_amount, user_id)
	VALUES ($1, $2, $3)
`

type InsertWithdrawalParams struct {
	OrderNum       int64
	WithdrawAmount pgtype.Numeric
	UserID         int64
}

func (q *Queries) InsertWithdrawal(ctx context.Context, arg InsertWithdrawalParams) error {
	_, err := q.db.Exec(ctx, insertWithdrawal, arg.OrderNum, arg.WithdrawAmount, arg.UserID)
	return err
}
