// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package balancerepository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Balance struct {
	ID        int64
	Amount    pgtype.Numeric
	Withdrawn pgtype.Numeric
	UserID    int64
}

type WithdrawHistory struct {
	ID             int64
	OrderNum       int64
	WithdrawAmount pgtype.Numeric
	UserID         int64
	CreatedAt      pgtype.Timestamp
}
