package main

const templateStr = `
// Code generated by go generate; DO NOT EDIT.
// This file was generated by reset.go

package {{.Package}}

{{range .Types}}
func (v *{{.Type}}) Reset() {
	if v == nil {
		return
	}
	{{- range .FieldResets}}
	{{.}}
	{{- end}}
}
{{end}}
`

const arrayResetTemplate = `{{.Receiver}}.{{.Name}} = {{.Receiver}}.{{.Name}}[:0]`

const arrayZeroTemplate = `{{.Receiver}}.{{.Name}} = {{.TypeName}}{}`

const mapResetTemplate = `if {{.Receiver}}.{{.Name}} != nil {
	clear({{.Receiver}}.{{.Name}})
}`

const chanCloseResetTemplate = `if {{.Receiver}}.{{.Name}} != nil {
	close({{.Receiver}}.{{.Name}})
	{{.Receiver}}.{{.Name}} = nil
}`

const valueResetTemplate = `{{.Receiver}}.{{.Name}} = {{.Value}}`

const callResetTemplate = `{{.Receiver}}.{{.Name}}.Reset()`

const zeroStructTemplate = `{{.Receiver}}.{{.Name}} = {{.TypeName}}{}`

const pointerResetTemplate = `if {{.Receiver}}.{{.Name}} != nil {
{{.InnerCode}}}`
