// Code generated by go generate; DO NOT EDIT.
// This file was generated by reset.go

package flagvalues

func (v *NetAddress) Reset() {
	if v == nil {
		return
	}
	v.Scheme = ""
	v.Host = ""
	v.SchemeRequired = false
}
