// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package urlsrepository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID           int32
	ShortUrl     string
	LongUrl      string
	UserID       pgtype.Int8
	CreatedAt    pgtype.Timestamp
	DeletedAtUtc pgtype.Timestamp
}
