// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: url_query.sql

package urlsrepository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getURLByShortURL = `-- name: GetURLByShortURL :one
SELECT id, short_url, long_url, created_at, user_id, deleted_at_utc
FROM urls
WHERE short_url = $1
LIMIT 1
`

type GetURLByShortURLRow struct {
	ID           int32
	ShortUrl     string
	LongUrl      string
	CreatedAt    pgtype.Timestamp
	UserID       pgtype.Int8
	DeletedAtUtc pgtype.Timestamp
}

func (q *Queries) GetURLByShortURL(ctx context.Context, shortUrl string) (GetURLByShortURLRow, error) {
	row := q.db.QueryRow(ctx, getURLByShortURL, shortUrl)
	var i GetURLByShortURLRow
	err := row.Scan(
		&i.ID,
		&i.ShortUrl,
		&i.LongUrl,
		&i.CreatedAt,
		&i.UserID,
		&i.DeletedAtUtc,
	)
	return i, err
}

const getURLsByUserID = `-- name: GetURLsByUserID :many
SELECT id, short_url, long_url, created_at, user_id, deleted_at_utc
FROM urls
WHERE user_id = $1
`

type GetURLsByUserIDRow struct {
	ID           int32
	ShortUrl     string
	LongUrl      string
	CreatedAt    pgtype.Timestamp
	UserID       pgtype.Int8
	DeletedAtUtc pgtype.Timestamp
}

func (q *Queries) GetURLsByUserID(ctx context.Context, userID pgtype.Int8) ([]GetURLsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getURLsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetURLsByUserIDRow
	for rows.Next() {
		var i GetURLsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ShortUrl,
			&i.LongUrl,
			&i.CreatedAt,
			&i.UserID,
			&i.DeletedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getURLsStats = `-- name: GetURLsStats :one
SELECT
  COUNT(DISTINCT long_url)::bigint AS unique_long_url_count,
  COUNT(DISTINCT user_id)::bigint AS unique_user_id_count
FROM urls
`

type GetURLsStatsRow struct {
	UniqueLongUrlCount int64
	UniqueUserIDCount  int64
}

func (q *Queries) GetURLsStats(ctx context.Context) (GetURLsStatsRow, error) {
	row := q.db.QueryRow(ctx, getURLsStats)
	var i GetURLsStatsRow
	err := row.Scan(&i.UniqueLongUrlCount, &i.UniqueUserIDCount)
	return i, err
}

const storeBatchUrls = `-- name: StoreBatchUrls :many
SELECT
  CAST(f.short_url AS text) AS short_url,
  CAST(f.long_url AS text) AS long_url,
  CAST(f.stored_short_url AS text) AS stored_short_url,
  CAST(f.retry AS boolean) AS retry
FROM LATERAL public.store_batch_urls($1::text[], $2::text[], $3) AS f(short_url, long_url, stored_short_url, retry)
`

type StoreBatchUrlsParams struct {
	LongUrls  []string
	ShortUrls []string
	UserID    int64
}

type StoreBatchUrlsRow struct {
	ShortUrl       string
	LongUrl        string
	StoredShortUrl string
	Retry          bool
}

func (q *Queries) StoreBatchUrls(ctx context.Context, arg StoreBatchUrlsParams) ([]StoreBatchUrlsRow, error) {
	rows, err := q.db.Query(ctx, storeBatchUrls, arg.LongUrls, arg.ShortUrls, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoreBatchUrlsRow
	for rows.Next() {
		var i StoreBatchUrlsRow
		if err := rows.Scan(
			&i.ShortUrl,
			&i.LongUrl,
			&i.StoredShortUrl,
			&i.Retry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
