// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: url_query.sql

package urlsrepository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getURLByShortURL = `-- name: GetURLByShortURL :one
SELECT id, short_url, long_url, created_at, deleted_at_utc
FROM urls
WHERE short_url = $1
LIMIT 1
`

type GetURLByShortURLRow struct {
	ID           int32
	ShortUrl     string
	LongUrl      string
	CreatedAt    pgtype.Timestamp
	DeletedAtUtc pgtype.Timestamp
}

func (q *Queries) GetURLByShortURL(ctx context.Context, shortUrl string) (GetURLByShortURLRow, error) {
	row := q.db.QueryRow(ctx, getURLByShortURL, shortUrl)
	var i GetURLByShortURLRow
	err := row.Scan(
		&i.ID,
		&i.ShortUrl,
		&i.LongUrl,
		&i.CreatedAt,
		&i.DeletedAtUtc,
	)
	return i, err
}

const listURLsByUserID = `-- name: ListURLsByUserID :many
SELECT id, short_url, long_url, created_at, user_id, deleted_at_utc
FROM urls
WHERE user_id = $1
`

type ListURLsByUserIDRow struct {
	ID           int32
	ShortUrl     string
	LongUrl      string
	CreatedAt    pgtype.Timestamp
	UserID       pgtype.Int8
	DeletedAtUtc pgtype.Timestamp
}

func (q *Queries) ListURLsByUserID(ctx context.Context, userID pgtype.Int8) ([]ListURLsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listURLsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListURLsByUserIDRow
	for rows.Next() {
		var i ListURLsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ShortUrl,
			&i.LongUrl,
			&i.CreatedAt,
			&i.UserID,
			&i.DeletedAtUtc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
