// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package orderrepository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	OrderNum  int64
	Status    int32
	Accrual   pgtype.Numeric
	UserID    int64
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
