// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_query.sql

package orderrepository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrAddOrder = `-- name: GetOrAddOrder :one
WITH inserted AS (
	INSERT INTO public.orders(order_num, status, user_id)
		VALUES ($1, $2, $3)
	ON CONFLICT (order_num) DO NOTHING
	RETURNING order_num, status, user_id, created_at, updated_at
)
SELECT order_num, status, user_id, created_at, updated_at, true as is_new
FROM inserted
UNION ALL
SELECT order_num, status, user_id, created_at, updated_at, false as is_new
FROM orders
WHERE order_num = $1
  AND NOT EXISTS (SELECT 1 FROM inserted)
`

type GetOrAddOrderParams struct {
	OrderNum int64
	Status   int32
	UserID   int64
}

type GetOrAddOrderRow struct {
	OrderNum  int64
	Status    int32
	UserID    int64
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	IsNew     bool
}

func (q *Queries) GetOrAddOrder(ctx context.Context, arg GetOrAddOrderParams) (GetOrAddOrderRow, error) {
	row := q.db.QueryRow(ctx, getOrAddOrder, arg.OrderNum, arg.Status, arg.UserID)
	var i GetOrAddOrderRow
	err := row.Scan(
		&i.OrderNum,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsNew,
	)
	return i, err
}

const getOrdersByUser = `-- name: GetOrdersByUser :many
SELECT order_num, status, accrual, user_id, created_at, updated_at
	FROM orders
	where user_id = $1
`

func (q *Queries) GetOrdersByUser(ctx context.Context, userID int64) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.OrderNum,
			&i.Status,
			&i.Accrual,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnproccessedOrders = `-- name: GetUnproccessedOrders :many
WITH picked AS (
	SELECT order_num
	FROM orders
	WHERE status IN (0, 1)
	ORDER BY status DESC, created_at
	LIMIT $1
	FOR UPDATE SKIP LOCKED
)
UPDATE orders o
SET status = 1
FROM picked p
WHERE o.order_num = p.order_num
RETURNING o.order_num, o.status, o.accrual, o.user_id, o.created_at, o.updated_at
`

func (q *Queries) GetUnproccessedOrders(ctx context.Context, limit int32) ([]Order, error) {
	rows, err := q.db.Query(ctx, getUnproccessedOrders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.OrderNum,
			&i.Status,
			&i.Accrual,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :one
UPDATE public.orders
	SET status = $2, accrual = $3, updated_at = now()
	WHERE order_num = $1
	RETURNING order_num, status, accrual, user_id
`

type UpdateOrderParams struct {
	OrderNum int64
	Status   int32
	Accrual  pgtype.Numeric
}

type UpdateOrderRow struct {
	OrderNum int64
	Status   int32
	Accrual  pgtype.Numeric
	UserID   int64
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (UpdateOrderRow, error) {
	row := q.db.QueryRow(ctx, updateOrder, arg.OrderNum, arg.Status, arg.Accrual)
	var i UpdateOrderRow
	err := row.Scan(
		&i.OrderNum,
		&i.Status,
		&i.Accrual,
		&i.UserID,
	)
	return i, err
}
